from setuptools import setup, find_packages

setup(
    name='vital-vitalsigns-examples-python',
    version='0.1.3',
    author='Marc Hadfield',
    author_email='marc@vital.ai',
    description='VitalSigns Examples',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/vital-ai/vital-vitalsigns-examples-python',
    packages=find_packages(),
    license='Apache License 2.0',
    install_requires=[
            'vital-ai-vitalsigns>=0.1.28',
            'vital-ai-domain>=0.1.7',
            'vital-ai-nlp>=0.1.5',
            'vital-ai-social>=0.1.5',
            'vital-ai-aimp>=0.1.6',
            'vital-ai-haley>=0.1.5',
            'vital-ai-haley-taxonomy>=0.1.5',
            'vital-ai-haley-ml>=0.1.5',
            'vital-ai-haley-question>=0.1.5',
            'vital-ai-haley-kg>=0.1.22',
            'vital-ai-chat>=0.1.19',
            'vital-ai-wordnet>=0.1.5',
            # 'vital-logic>=0.1.0',
            'six',
            'pyyaml',
            'SPARQLWrapper',
            'weaviate-client',
            'nltk>=3.8.1',
            'rdflib',
            'uuid',
            'pyodbc',
            'psutil',
            'networkx',
            'matplotlib',
            'scipy',
            'numpy',
            'scikit-learn',
            'dill',
            'requests',
            # 'vital-model-chars2vec-onnx',
            'datasketch'
        ],
    classifiers=[
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.11',
)
